package visao;

public class FrmMovimentacao extends javax.swing.JFrame {

    private final dao.ProdutoDAO produtoDAO = new dao.ProdutoDAO();
    private final dao.MovimentacaoDAO movimentacaoDAO = new dao.MovimentacaoDAO();
    private int idMovimentacaoSelecionada = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMovimentacao.class.getName());

    /**
     * Creates new form FrmMovimentacao
     */
    public FrmMovimentacao() {
        initComponents();
        carregarProdutos();
        carregarTabela();
        verificarEstoqueMinimo();
        jButton4.setVisible(false);
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                preencherCamposComLinhaSelecionada();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProduto.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        lblProduto.setText("Movimentação");

        jLabel2.setText("ProdutoID:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Quantidade:");

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Aceitar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRADA", "SAIDA" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ProdutoID", "Data", "Quantidade", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Excluir");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText(" Clique em uma linha da tabela para editar ou excluir");

        jMenu1.setText("Movimentação");

        jMenuItem3.setText("Início");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        jMenuItem1.setText("Produto");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Categoria");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 117, Short.MAX_VALUE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblProduto))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(13, 13, 13)
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarMovimentacao();
        verificarEstoqueMinimo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        idMovimentacaoSelecionada = -1;
        jButton1.setText("Ok");
        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setVisible(false);
        jTable1.clearSelection();
        jSpinner1.setValue(0);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jButton4.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Clique em uma linha da tabela para selecionar.",
                    "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        int id = (int) model.getValueAt(linha, 0);

        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir a movimentação ID " + id + "?",
                "Confirmar exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            movimentacaoDAO.remover(id);
            idMovimentacaoSelecionada = -1;
            jButton1.setText("Ok");
            jButton1.setBackground(new java.awt.Color(0, 153, 204));
            jTable1.clearSelection();
            jSpinner1.setValue(0);
            carregarTabela();
            verificarEstoqueMinimo();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Movimentação excluída com sucesso!",
                    "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         new FrmCategoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new FrmMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           new FrmProduto().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void carregarProdutos() {
        jComboBox2.removeAllItems();
        java.util.List<modelo.Produto> produtos = produtoDAO.listar();
        if (produtos.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Nenhum produto cadastrado.", "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        for (modelo.Produto p : produtos) {
            jComboBox2.addItem(p.getNome() + " (ID:" + p.getId() + ")");
        }
    }

    private void carregarTabela() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        java.util.List<modelo.Movimentacao> lista = movimentacaoDAO.listar();
        for (modelo.Movimentacao m : lista) {
            model.addRow(new Object[]{
                m.getId(),
                m.getProduto().getNome(),
                m.getData(),
                m.getQuantidade(),
                m.getTipo().name()
            });
        }
    }

    private modelo.Produto getProdutoSelecionado() {
        int idx = jComboBox2.getSelectedIndex();
        if (idx < 0) {
            return null;
        }
        java.util.List<modelo.Produto> produtos = produtoDAO.listar();
        return produtos.get(idx);
    }

    private void registrarMovimentacao() {
        modelo.Produto produto = getProdutoSelecionado();
        if (produto == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecione um produto.", "Atenção",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tipo = (String) jComboBox1.getSelectedItem();
        int quantidade = (int) jSpinner1.getValue();

        if (quantidade <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "A quantidade deve ser maior que zero.", "Atenção",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        modelo.Produto prodAtual = produtoDAO.buscarPorId(produto.getId());

        if (idMovimentacaoSelecionada >= 0) {
            // MODO EDIÇÃO — atualiza o registro existente
            modelo.Movimentacao mov = new modelo.Movimentacao();
            mov.setId(idMovimentacaoSelecionada);
            mov.setProduto(prodAtual);
            mov.setData(java.time.LocalDate.now());
            mov.setQuantidade(quantidade);
            mov.setTipo(enums.TipoMovimentacao.valueOf(tipo));
            movimentacaoDAO.atualizar(mov);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Movimentação atualizada com sucesso!",
                    "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Volta ao modo inserção
            idMovimentacaoSelecionada = -1;
            jButton1.setText("Ok");
            jButton1.setBackground(new java.awt.Color(0, 153, 204));
            jTable1.clearSelection();

        } else {
            // MODO INSERÇÃO — lógica original
            if ("ENTRADA".equals(tipo)) {
                int novaQtd = prodAtual.getQuantidade() + quantidade;
                if (novaQtd > prodAtual.getQuantidadeMaxima()) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "⚠ Estoque máximo excedido!\n\n"
                            + "Produto: " + prodAtual.getNome() + "\n"
                            + "Estoque atual: " + prodAtual.getQuantidade() + "\n"
                            + "Quantidade a adicionar: " + quantidade + "\n"
                            + "Total resultante: " + novaQtd + "\n"
                            + "Máximo permitido: " + prodAtual.getQuantidadeMaxima() + "\n\n"
                            + "Operação cancelada.",
                            "Limite Máximo", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                prodAtual.entradaEstoque(quantidade);
            } else {
                if (quantidade > prodAtual.getQuantidade()) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "⚠ Estoque insuficiente!\n\n"
                            + "Produto: " + prodAtual.getNome() + "\n"
                            + "Estoque atual: " + prodAtual.getQuantidade() + "\n"
                            + "Quantidade solicitada: " + quantidade + "\n\n"
                            + "Operação cancelada.",
                            "Estoque Insuficiente", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                prodAtual.saidaEstoque(quantidade);
            }

            produtoDAO.atualizar(prodAtual);

            modelo.Movimentacao mov = new modelo.Movimentacao();
            mov.setProduto(prodAtual);
            mov.setData(java.time.LocalDate.now());
            mov.setQuantidade(quantidade);
            mov.setTipo(enums.TipoMovimentacao.valueOf(tipo));
            movimentacaoDAO.inserir(mov);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Movimentação registrada!\n\nProduto: " + prodAtual.getNome()
                    + "\nTipo: " + tipo
                    + "\nQuantidade: " + quantidade
                    + "\nNovo estoque: " + prodAtual.getQuantidade(),
                    "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        carregarProdutos();
        carregarTabela();
        jSpinner1.setValue(0);
        verificarEstoqueMinimo();
    }

    private void verificarEstoqueMinimo() {
        java.util.List<modelo.Produto> produtos = produtoDAO.listar();
        StringBuilder alertas = new StringBuilder();
        for (modelo.Produto p : produtos) {
            if (p.abaixoMinimo()) {
                alertas.append("ALERTA: ")
                        .append(p.getNome())
                        .append(" está abaixo do estoque mínimo! ")
                        .append("(atual: ").append(p.getQuantidade())
                        .append(", mínimo: ").append(p.getQuantidadeMinima())
                        .append(")  ");
            }
        }
        if (alertas.length() > 0) {
            jLabel6.setText(alertas.toString());
        } else {
            jLabel6.setText("");
        }
    }

    private void preencherCamposComLinhaSelecionada() {
        int linha = jTable1.getSelectedRow();
        if (linha < 0) {
            return;
        }
        jButton3.setVisible(true);
        jButton4.setVisible(true);

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        idMovimentacaoSelecionada = (int) model.getValueAt(linha, 0);
        String nomeProduto = (String) model.getValueAt(linha, 1);
        int qtd = (int) model.getValueAt(linha, 3);
        String tipoStr = (String) model.getValueAt(linha, 4);

        // Seleciona o produto na combobox
        for (int i = 0; i < jComboBox2.getItemCount(); i++) {
            if (jComboBox2.getItemAt(i).startsWith(nomeProduto)) {
                jComboBox2.setSelectedIndex(i);
                break;
            }
        }

        jComboBox1.setSelectedItem(tipoStr);
        jSpinner1.setValue(qtd);

        jButton1.setText("Salvar Edição");
        jButton1.setBackground(new java.awt.Color(255, 140, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMovimentacao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProduto;
    // End of variables declaration//GEN-END:variables
}
