package visao;

import dao.CategoriaDAO;
import dao.ProdutoDAO;
import modelo.Categoria;
import modelo.Produto;
import constante.Unidade;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Formulário de gerenciamento de produtos. Permite cadastrar, editar e excluir
 * produtos, exibindo os registros em uma tabela e navegando para outras telas
 * pelo menu.
 *
 * @author Luigi
 */
public class FrmProduto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProduto.class.getName());

    /**
     * Construtor da tela de produtos. Inicializa os componentes visuais,
     * carrega as categorias no combo, carrega a tabela com os dados do banco e
     * registra o listener de clique na tabela para preencher automaticamente os
     * campos do formulário.
     */
    public FrmProduto() {
        initComponents();
        carregarCategorias();
        carregarTabela();
        TblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                preencherFormulario();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProdutos = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txtNome10 = new javax.swing.JLabel();
        bntAdicionar5 = new javax.swing.JButton();
        btnEditar5 = new javax.swing.JButton();
        btnExcluir5 = new javax.swing.JButton();
        lblEmbalagem5 = new javax.swing.JLabel();
        lblNome = new javax.swing.JTextField();
        txtNome13 = new javax.swing.JLabel();
        cmbUnidade = new javax.swing.JComboBox<>();
        txtNome14 = new javax.swing.JLabel();
        txtNome15 = new javax.swing.JLabel();
        lblEmbalagem6 = new javax.swing.JLabel();
        txtNome24 = new javax.swing.JLabel();
        campQuantidade = new javax.swing.JTextField();
        campQtdMinima = new javax.swing.JTextField();
        campQtdMaxima = new javax.swing.JTextField();
        campPreco = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produto");

        lblProduto.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        lblProduto.setText("Produto");

        TblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "PREÇO", "QTDE", "QTD.MIN", "QTD.MAX", "UNIDADE", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblProdutos);

        txtNome10.setText("Nome:");

        bntAdicionar5.setBackground(new java.awt.Color(46, 204, 113));
        bntAdicionar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAdicionar5.setText("Adicionar");
        bntAdicionar5.addActionListener(this::bntAdicionar5bntAdicionarActionPerformed);

        btnEditar5.setBackground(new java.awt.Color(0, 153, 204));
        btnEditar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar5.setText("Editar");
        btnEditar5.addActionListener(this::btnEditar5btnEditarActionPerformed);

        btnExcluir5.setBackground(new java.awt.Color(231, 76, 60));
        btnExcluir5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir5.setText("Excluir");
        btnExcluir5.addActionListener(this::btnExcluir5btnExcluirActionPerformed);

        lblEmbalagem5.setText("Preço:");

        lblNome.addActionListener(this::lblNomeActionPerformed);

        txtNome13.setText("Unidade de Medida:");

        cmbUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UN", "KG", "G", "L", "ML" }));
        cmbUnidade.addActionListener(this::cmbUnidadeActionPerformed);

        txtNome14.setText("Categoria:");

        txtNome15.setText("Qnt/minima:");

        lblEmbalagem6.setText("Qnt/maxima:");

        txtNome24.setText("Qnt/estoque:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(bntAdicionar5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir5))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmbalagem5)
                            .addComponent(txtNome13)
                            .addComponent(txtNome10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUnidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNome)
                            .addComponent(campPreco))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmbalagem6)
                    .addComponent(txtNome15)
                    .addComponent(txtNome14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campQtdMinima, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(campQtdMaxima)
                    .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome10)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome13)
                            .addComponent(cmbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblEmbalagem5))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome14)
                            .addComponent(txtNome24)
                            .addComponent(campQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome15)
                            .addComponent(campQtdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmbalagem6)
                            .addComponent(campQtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar5)
                    .addComponent(bntAdicionar5)
                    .addComponent(btnExcluir5))
                .addContainerGap())
        );

        jMenu1.setText("Movimentação");

        jMenuItem3.setText("Gerenciar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        jMenuItem1.setText("Início");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Categoria");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Reajuste/preço");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduto))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Ação do menu Início. Abre a tela {@link FrmPrincipal} e fecha a tela
     * atual.
     *
     * @param evt evento de clique do item de menu.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FrmPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * Ação do botão Adicionar. Valida os campos, cria um novo {@link Produto}
     * com os dados informados e o persiste no banco via {@link ProdutoDAO}.
     * Verifica se a quantidade máxima é maior que a mínima antes de salvar.
     * Exibe mensagem de sucesso, limpa o formulário e recarrega a tabela.
     *
     * @param evt evento de clique do botão.
     */
    private void bntAdicionar5bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionar5bntAdicionarActionPerformed
        if (lblNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do produto!");
            return;
        }
        try {
            Produto produto = new Produto();
            produto.setNome(lblNome.getText().trim());
            produto.setPreco(Double.parseDouble(campPreco.getText().trim()));
            produto.setQuantidade(Integer.parseInt(campQuantidade.getText().trim()));
            int qtdMinima = Integer.parseInt(campQtdMinima.getText().trim());
            int qtdMaxima = Integer.parseInt(campQtdMaxima.getText().trim());
            if (qtdMaxima <= qtdMinima) {
                JOptionPane.showMessageDialog(this, "A quantidade máxima deve ser maior que a quantidade mínima!");
                return;
            }
            produto.setQuantidadeMinima(qtdMinima);
            produto.setQuantidadeMaxima(qtdMaxima);
            produto.setUnidade(Unidade.valueOf(cmbUnidade.getSelectedItem().toString()));
            produto.setCategoria((Categoria) cmbCategoria.getSelectedItem());

            new ProdutoDAO().cadastrar(produto);
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            limparFormulario();
            carregarTabela();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifique os campos numéricos.");
        }
    }//GEN-LAST:event_bntAdicionar5bntAdicionarActionPerformed
    /**
     * Ação do botão Editar. Valida se uma linha está selecionada e os campos
     * estão preenchidos corretamente, então atualiza o {@link Produto}
     * correspondente no banco via {@link ProdutoDAO}. Verifica se a quantidade
     * máxima é maior que a mínima antes de salvar. Exibe mensagem de sucesso,
     * limpa o formulário e recarrega a tabela.
     *
     * @param evt evento de clique do botão.
     */
    private void btnEditar5btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar5btnEditarActionPerformed
        int linha = TblProdutos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para editar.");
            return;
        }
        try {
            Produto produto = new Produto();
            produto.setId((int) TblProdutos.getValueAt(linha, 0));
            produto.setNome(lblNome.getText().trim());
            produto.setPreco(Double.parseDouble(campPreco.getText().trim()));
            produto.setQuantidade(Integer.parseInt(campQuantidade.getText().trim()));
            int qtdMinima = Integer.parseInt(campQtdMinima.getText().trim());
            int qtdMaxima = Integer.parseInt(campQtdMaxima.getText().trim());
            if (qtdMaxima <= qtdMinima) {
                JOptionPane.showMessageDialog(this, "A quantidade máxima deve ser maior que a quantidade mínima!");
                return;
            }
            produto.setQuantidadeMinima(qtdMinima);
            produto.setQuantidadeMaxima(qtdMaxima);
            produto.setUnidade(Unidade.valueOf(cmbUnidade.getSelectedItem().toString()));
            produto.setCategoria((Categoria) cmbCategoria.getSelectedItem());

            new ProdutoDAO().atualizar(produto);
            JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");
            limparFormulario();
            carregarTabela();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifique os campos numéricos.");
        }
    }//GEN-LAST:event_btnEditar5btnEditarActionPerformed
    /**
     * Ação do botão Excluir. Valida se uma linha está selecionada na tabela,
     * solicita confirmação ao usuário e remove o {@link Produto} correspondente
     * no banco via {@link ProdutoDAO}. Exibe mensagem de sucesso, limpa o
     * formulário e recarrega a tabela.
     *
     * @param evt evento de clique do botão.
     */
    private void btnExcluir5btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir5btnExcluirActionPerformed
        int linha = TblProdutos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para excluir.");
            return;
        }
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Deseja realmente excluir este produto?",
                "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            new ProdutoDAO().remover((int) TblProdutos.getValueAt(linha, 0));
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
            limparFormulario();
            carregarTabela();
        }
    }//GEN-LAST:event_btnExcluir5btnExcluirActionPerformed

    private void lblNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeActionPerformed

    private void cmbUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnidadeActionPerformed
    /**
     * Ação do menu Categoria. Abre a tela {@link FrmCategoria} e fecha a tela
     * atual.
     *
     * @param evt evento de clique do item de menu.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FrmCategoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * Ação do menu Movimentação. Abre a tela {@link FrmMovimentacao} e fecha a
     * tela atual.
     *
     * @param evt evento de clique do item de menu.
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new FrmMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    /**
     * Ação do menu Reajuste/preço. Abre a tela {@link FrmReajustar} e fecha a
     * tela atual.
     *
     * @param evt evento de clique do item de menu.
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new FrmReajustar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProduto().setVisible(true));
    }

    /**
     * Carrega todas as categorias cadastradas no banco via {@link CategoriaDAO}
     * e popula o combo {@code cmbCategoria}, limpando os itens anteriores.
     */
    private void carregarCategorias() {
        cmbCategoria.removeAllItems();
        for (modelo.Categoria c : new dao.CategoriaDAO().listar()) {
            cmbCategoria.addItem(c);
        }
    }

    /**
     * Carrega ou recarrega os dados da tabela {@code TblProdutos} buscando
     * todos os produtos no banco via {@link ProdutoDAO}. Limpa as linhas
     * existentes antes de popular novamente. O preço é formatado com duas casas
     * decimais e a categoria exibe apenas o nome.
     */
    private void carregarTabela() {
        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) TblProdutos.getModel();
        modelo.setRowCount(0);
        for (modelo.Produto p : new dao.ProdutoDAO().listar()) {
            modelo.addRow(new Object[]{
                p.getId(), p.getNome(),
                String.format("%.2f", p.getPreco()),
                p.getQuantidade(), p.getQuantidadeMinima(), p.getQuantidadeMaxima(),
                p.getUnidade().name(),
                p.getCategoria() != null ? p.getCategoria().getNome() : ""
            });
        }
    }

    /**
     * Limpa todos os campos do formulário, redefinindo os valores padrão dos
     * campos de texto, combos e removendo a seleção da tabela.
     */
    private void limparFormulario() {
        lblNome.setText("");
        campPreco.setText("");
        campQuantidade.setText("");
        campQtdMinima.setText("");
        campQtdMaxima.setText("");
        cmbUnidade.setSelectedIndex(0);
        if (cmbCategoria.getItemCount() > 0) {
            cmbCategoria.setSelectedIndex(0);
        }
        TblProdutos.clearSelection();
    }

    /**
     * Preenche os campos do formulário com os dados da linha selecionada na
     * tabela {@code TblProdutos}. Seleciona automaticamente a unidade e a
     * categoria correspondentes nos combos.
     */
    private void preencherFormulario() {
        int linha = TblProdutos.getSelectedRow();
        if (linha == -1) {
            return;
        }
        lblNome.setText(TblProdutos.getValueAt(linha, 1).toString());
        campPreco.setText(TblProdutos.getValueAt(linha, 2).toString());
        campQuantidade.setText(TblProdutos.getValueAt(linha, 3).toString());
        campQtdMinima.setText(TblProdutos.getValueAt(linha, 4).toString());
        campQtdMaxima.setText(TblProdutos.getValueAt(linha, 5).toString());
        String unidade = TblProdutos.getValueAt(linha, 6).toString();
        cmbUnidade.setSelectedItem(unidade);
        String nomeCat = TblProdutos.getValueAt(linha, 7).toString();
        for (int i = 0; i < cmbCategoria.getItemCount(); i++) {
            if (cmbCategoria.getItemAt(i).getNome().equals(nomeCat)) {
                cmbCategoria.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblProdutos;
    private javax.swing.JButton bntAdicionar5;
    private javax.swing.JButton btnEditar5;
    private javax.swing.JButton btnExcluir5;
    private javax.swing.JTextField campPreco;
    private javax.swing.JTextField campQtdMaxima;
    private javax.swing.JTextField campQtdMinima;
    private javax.swing.JTextField campQuantidade;
    private javax.swing.JComboBox<Categoria> cmbCategoria;
    private javax.swing.JComboBox<String> cmbUnidade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmbalagem5;
    private javax.swing.JLabel lblEmbalagem6;
    private javax.swing.JTextField lblNome;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel txtNome10;
    private javax.swing.JLabel txtNome13;
    private javax.swing.JLabel txtNome14;
    private javax.swing.JLabel txtNome15;
    private javax.swing.JLabel txtNome24;
    // End of variables declaration//GEN-END:variables
}
