/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProdutoDAO;
import javax.swing.JOptionPane;
import model.Categoria;
import model.Produto;
import dao.CategoriaDAO;
import java.util.List;
import model.Unidade;

/**
 *
 * @author sdews
 */
public class FrmAddProduto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAddProduto.class.getName());

    private List<Categoria> categorias;

    public FrmAddProduto() {
        initComponents();
        carregarCategorias(); // linha adicionada
    }

    private void carregarCategorias() {
        CategoriaDAO dao = new CategoriaDAO();
        categorias = dao.listar();
        jCategoriaSelect.removeAllItems();
        for (Categoria cat : categorias) {
            jCategoriaSelect.addItem(cat.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        undprd = new javax.swing.JTextField();
        nomeprd = new javax.swing.JTextField();
        precoprd = new javax.swing.JTextField();
        estoqueprd = new javax.swing.JTextField();
        maxprd = new javax.swing.JTextField();
        minprd = new javax.swing.JTextField();
        jCategoriaSelect = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adicionar Produto");

        jLabel1.setText("Nome:");

        jLabel2.setText("Preço:");

        jLabel3.setText("Unidade de medida:");

        jLabel4.setText("Quantidade no Estoque:");

        jLabel5.setText("Quantidade Mínima:");

        jLabel6.setText("Quantidade Maxima:");

        jLabel7.setText("Categoria:");

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel8.setText("PRODUTO");

        undprd.setToolTipText("Digite a unidade do Produto. Ex Kg, Un");
        undprd.addActionListener(this::undprdActionPerformed);

        nomeprd.setToolTipText("Digite o nome do Produto");
        nomeprd.setActionCommand("<Not Set>");
        nomeprd.addActionListener(this::nomeprdActionPerformed);

        precoprd.setToolTipText("Digite o preço do Produto");
        precoprd.addActionListener(this::precoprdActionPerformed);

        estoqueprd.addActionListener(this::estoqueprdActionPerformed);

        maxprd.addActionListener(this::maxprdActionPerformed);

        minprd.addActionListener(this::minprdActionPerformed);

        jCategoriaSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "pao" }));
        jCategoriaSelect.addActionListener(this::jCategoriaSelectActionPerformed);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Voltar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jMenu3.setText("Movimentação");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Opções");

        jMenu1.setText("Categoria");

        jMenuItem1.setText("Adicionar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Alterar");
        jMenu1.add(jMenuItem4);

        jMenu2.add(jMenu1);

        jMenu4.setText("Produto");

        jMenuItem3.setText("Voltar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu4.add(jMenuItem3);

        jMenuItem5.setText("Alterar");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeprd, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCategoriaSelect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(undprd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(precoprd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(minprd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxprd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(estoqueprd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(precoprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCategoriaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estoqueprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        nomeprd.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void undprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undprdActionPerformed

    private void nomeprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeprdActionPerformed

    private void precoprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoprdActionPerformed

    private void estoqueprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estoqueprdActionPerformed

    private void maxprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxprdActionPerformed

    private void minprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minprdActionPerformed

    private void jCategoriaSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriaSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCategoriaSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nomeprd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do produto!");
            return;
        }

        if (categorias == null || categorias.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cadastre uma categoria antes de adicionar um produto!");
            return;
        }

        try {
            Produto produto = new Produto();

            produto.setNome(nomeprd.getText().trim());
            produto.setPreco(Double.parseDouble(precoprd.getText().trim()));
            produto.setUnidade(
                    Unidade.valueOf(
                            undprd.getText().trim().toUpperCase()
                    )
            );
            produto.setQuantidade(Integer.parseInt(estoqueprd.getText().trim()));
            produto.setQuantidadeMinima(Integer.parseInt(minprd.getText().trim()));
            produto.setQuantidadeMaxima(Integer.parseInt(maxprd.getText().trim()));

            Categoria categoria = categorias.get(jCategoriaSelect.getSelectedIndex());
            produto.setCategoria(categoria);

            ProdutoDAO dao = new ProdutoDAO();
            dao.cadastrar(produto);

            JOptionPane.showMessageDialog(null, "Produto cadastrado!");

            nomeprd.setText("");
            precoprd.setText("");
            undprd.setText("");
            estoqueprd.setText("");
            minprd.setText("");
            maxprd.setText("");
            jCategoriaSelect.setSelectedIndex(0);

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this,
                    "Unidade inválida! Use: UN, KG, G, L ou ML");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmAddCategoria object = new FrmAddCategoria();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FrmAltProduto object = new FrmAltProduto();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAddProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estoqueprd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCategoriaSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JTextField maxprd;
    private javax.swing.JTextField minprd;
    private javax.swing.JTextField nomeprd;
    private javax.swing.JTextField precoprd;
    private javax.swing.JTextField undprd;
    // End of variables declaration//GEN-END:variables
}
